# Generated by Django 3.2.8 on 2021-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('cli_apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('cli_celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('cli_direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('cli_recomendaciones', models.TextField(verbose_name='Recomendaciones')),
            ],
        ),
    ]
