# Generated by Django 3.2.8 on 2021-10-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, verbose_name='Producto')),
                ('product_price', models.IntegerField(verbose_name='Precio')),
                ('product_description', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
        ),
    ]
