# Generated by Django 3.2.8 on 2021-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='product_description',
        ),
        migrations.AddField(
            model_name='producto',
            name='product_tipo',
            field=models.CharField(default=0.0010390895596239485, max_length=100, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
