# Generated by Django 3.2.8 on 2021-10-22 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20211022_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('pedido_cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('pedido_prducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.producto')),
            ],
        ),
    ]
