# Generated by Django 3.2.8 on 2021-10-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_fecha',
        ),
    ]
