# Generated by Django 3.2.8 on 2021-10-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_remove_pedido_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restapi.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_prducto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restapi.producto'),
        ),
    ]
