# Generated by Django 3.2.8 on 2021-10-23 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20211022_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pedido_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_prducto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.producto'),
        ),
    ]
